ktor:
    application:
        modules:
            - example.com.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  issuer: "http://localhost"
  audience: "my-audience"
  realm: "my realm"
  secret: ${SECRET}
